server:
  port: 9012

spring:
  application:
    name: jiehuihui-gateway #指定服务名
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: jiehuihui_web_body #路由ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:5001  #匹配后提供服务的路由地址
          uri: lb://jiehuihui-web-body
          predicates:
            - Path=/admin/**,/login/** #断言，路径相匹配的进行路由

eureka:
  client:
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://127.0.0.1:6868/eureka/
      register-with-eureka: true
      fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: cloud-gateway-service
