#开发环境
#端口
server:
  port: 5001

#mysq;
spring:
  application:
    name: jiehuihui-web-body #指定服务名
  datasource:
    url: jdbc:mysql://192.168.1.103:3306/jiehuihui?useUnicode=true&characterEncoding=utf8
#    url: jdbc:mysql://144.48.9.35:3377/jiehuihui?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
#    password: jiehuihui520
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
#    host: 144.48.9.35
    host: 192.168.1.103
    port: 6379
#    password: jiehuihui520
    password: 123456
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池中的最大空闲连接  #
        max-idle: 10
    # 连接超时时间（毫秒）
    timeout: 1000


#下面代码注册到nacos里面
#  cloud:
#    nacos:
#      discovery:
#        ###服务注册Nacos地址
#        server-addr: 127.0.0.1:8848


#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:6868/eureka  #注册中心服务地址
#  instance:
#    prefer-ip-address: true  #注册中心以ip地址形式注册

#配置mybatisplus
mybatis-plus:
  mapper-locations: classpath*:/mapper/**.xml


#配置redis

#日志
#logging.file=ec.log
#logging:
#  config: classpath:logback.xml

